# Generated by Django 5.2.8 on 2025-12-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FireDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('bright_ti4', models.FloatField()),
                ('scan', models.FloatField()),
                ('track', models.FloatField()),
                ('acq_date', models.DateField()),
                ('acq_time', models.CharField(max_length=4)),
                ('satellite', models.CharField(max_length=10)),
                ('instrument', models.CharField(max_length=10)),
                ('confidence', models.CharField(max_length=1)),
                ('version', models.CharField(max_length=10)),
                ('bright_ti5', models.FloatField()),
                ('frp', models.FloatField()),
                ('daynight', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'fire_detection',
            },
        ),
    ]
